### ISSUE TITLE
Watcher error

### ISSUE THREAD

**Issue by Narno** [PHPoole/PHPoole#127]
```shell
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Yosymfony\ResourceWatcher\ResourceWatcher::__construct(), 1 passed in phar:///usr/local/bin/phpoole/src/Command/Serve.php on line 69 and exactly 3 expected in phar:///usr/local/bin/phpoole/vendor/yosymfony/resource-watcher/src/ResourceWatcher.php:41
Stack trace:
#0 phar:///usr/local/bin/phpoole/src/Command/Serve.php(69): Yosymfony\ResourceWatcher\ResourceWatcher->__construct(Object(Yosymfony\ResourceWatcher\ResourceCacheMemory))
#1 phar:///usr/local/bin/phpoole/src/Command/AbstractCommand.php(63): PHPoole\Command\Serve->processCommand()
#2 [internal function]: PHPoole\Command\AbstractCommand->__invoke(Object(ZF\Console\Route), Object(Zend\Console\Adapter\Posix))
#3 phar:///usr/local/bin/phpoole/src/Command/Build.php(50): call_user_func(Object(PHPoole\Command\Serve), Object(ZF\Console\Route), Object(Zend\Console\Adapter\Posix))
#4 phar:///usr/local/bin/phpoole/src/Command/AbstractCommand.php(63): PHPoole\Command\Build->processCommand()
#5 [internal fun in phar:///usr/local/bin/phpoole/vendor/yosymfony/resource-watcher/src/ResourceWatcher.php on line 41
```

Ref.: `yosymfony/resource-watcher`

**Comment by Narno** [comment]
`ResourceWatcher` require 3 arguments since version 2: https://github.com/yosymfony/Resource-watcher#how-to-use.

```php
use Yosymfony\ResourceWatcher\Crc32ContentHash;

$finder = new Finder();
$finder->files()
    ->name('*.md')
    ->name('*.twig')
    ->in([
        $this->getPath().'/'.$this->getPHPoole()->getConfig()->get('content.dir'),
        $this->getPath().'/'.$this->getPHPoole()->getConfig()->get('layouts.dir'),
    ]);
if (is_dir($this->getPath().'/'.$this->getPHPoole()->getConfig()->get('themes.dir'))) {
    $finder->in($this->getPath().'/'.$this->getPHPoole()->getConfig()->get('themes.dir'));
}
$hashContent = new Crc32ContentHash();
$resourceCache = new ResourceCacheMemory();
$resourceWatcher = new ResourceWatcher($resourceCache, $finder, $hashContent);
```
